[package]
name = "kanna-chan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.36.0", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "io-util",
] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
figment = { version = "0.10.14", features = ["env", "toml", "json"] }
reqwest = { version = "0.11.24", features = [
    "tokio-rustls",
    "json",
    "rustls",
    "rustls-tls",
], default-features = false }
clap = { version = "4.3.0", features = ["derive"] }
open = "5.1.1"
scanln = "0.1.1"
toml = "0.8.10"
tonic = "0.11.0"
prost = "0.12.3"
anyhow = "1.0.81"
lazy_static = "1.4.0"

[build-dependencies]
tonic-build = "0.11"
